language: python

matrix:
    include:
        - os: linux
          sudo: required
          python: 2.7

        # travis doesn't support py2.7: https://github.com/travis-ci/travis-ci/issues/2312

install:
    - pip install pyinstaller pep8
    - git clone https://github.com/vivisect/vivtestfiles.git /tmp/vivtestfiles
    - pip install -e .

script:
    - find . -name \*.py -exec pep8 --ignore=E501 {} \;
    - py.test -v
