os:
    - linux

env:
    - VIVTESTFILES=/tmp/vivtestfiles

sudo: required
dist: bionic

language: python

python:
    - "2.7"

virtualenv:
  system_site_packages: true

install:
    - pip install pyinstaller pep8
    - git clone https://github.com/vivisect/vivtestfiles.git /tmp/vivtestfiles
    - "travis_retry sudo apt-get -qq install libfreetype6-dev liblcms2-dev libqt5gui5 python-pyqt5 python-pyqt5.qtwebkit ghostscript libffi-dev libjpeg-turbo-progs cmake imagemagick"
    - pip install msgpack-python cxxfilt
    - pip install -e .

script:
    - find . -name \*.py -exec pep8 --ignore=E501 {} \;
    - py.test -v
